package testtypes

// dummy file, not actually generated by the test
// its for checking that easynbt does NOT complain about a method named "TagType"
// already existing on that type, because its in the target file (which is specified as this one)

func (h *HasTagTypeButOnlyInTargetFile) TagType() byte {
	return 0
}
